version: "3.8"

services:
    # Service PHP
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    #Servivce NPM
    node:
        image: node:20
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: sh -c "npm install && npm run build"

    # Service MySQL
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - laravel

    # Service Nginx
    webserver:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
